# Generated by Django 5.0.7 on 2024-12-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='bairro',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='doctor',
            name='contacto_de_emergencia',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='doctor',
            name='nr_casa',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='doctor',
            name='quarteirao',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
