# Generated by Django 5.0.7 on 2024-12-01 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_doctor_bairro_doctor_contacto_de_emergencia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='contacto_de_emergencia',
            new_name='block',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='nr_casa',
            new_name='emergency_contact',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='quarteirao',
            new_name='house_number',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='bairro',
            new_name='neighborhood',
        ),
    ]
