# Generated by Django 5.0.7 on 2024-10-14 15:35

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nid', models.CharField(default=core.models.Patient.generate_nid, editable=False, max_length=9, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('genero', models.CharField(max_length=10)),
                ('endereco', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=20)),
                ('contacto_de_emergencia', models.CharField(blank=True, max_length=15)),
                ('contacto_familia', models.CharField(blank=True, max_length=15)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('bairro', models.CharField(blank=True, max_length=60)),
                ('quarteirao', models.CharField(blank=True, max_length=15)),
                ('nr_casa', models.CharField(blank=True, max_length=15)),
                ('data_entrada', models.DateTimeField()),
                ('estado', models.CharField(choices=[('grave', 'Grave'), ('ligeiro', 'Ligeiro')], max_length=20)),
                ('tipo', models.CharField(blank=True, choices=[('estudante', 'Estudante'), ('bolseiro', 'Bolseiro'), ('docente', 'Docente'), ('funcionario(cta)', 'Funcionacio(CTA)'), ('comunidade', 'comunidade'), ('externo', 'Externo')], max_length=60, null=True)),
                ('nr_estudante', models.CharField(blank=True, max_length=9, null=True)),
                ('nr_funcionario', models.CharField(blank=True, max_length=9, null=True)),
            ],
        ),
    ]
