# Generated by Django 5.0.7 on 2024-12-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('genero', models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino')], max_length=20)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('data_nascimento', models.DateField()),
                ('data_contratacao', models.DateTimeField()),
                ('especialidade', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
