# Generated by Django 5.0.7 on 2024-10-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nid', models.CharField(help_text='Patient NID', max_length=20)),
                ('patient_name', models.CharField(max_length=100)),
                ('exam', models.CharField(choices=[('hemograma', 'Hemograma'), ('glicose', 'Glicose'), ('colesterol_total', 'Colesterol Total'), ('triglicerídeos', 'Triglicerídeos'), ('função_hepatica', 'Função Hepática'), ('função_renal', 'Função Renal'), ('urina_geral', 'Urina Geral'), ('exame_sanguineo', 'Exame Sanguíneo'), ('raio_x', 'Raio X'), ('ultrassom', 'Ultrassom'), ('tomografia_computadorizada', 'Tomografia Computadorizada'), ('ressonancia_magnetica', 'Ressonância Magnética'), ('ecocardiograma', 'Ecocardiograma'), ('teste_de_esforço', 'Teste de Esforço'), ('exame_de_visao', 'Exame de Visão'), ('exame_de_auditivo', 'Exame Auditivo'), ('cultura_de_bactéria', 'Cultura de Bactéria'), ('teste_rápido', 'Teste Rápido'), ('bioquimica', 'Bioquímica'), ('imunologia', 'Imunologia'), ('alergia', 'Alergia')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nid', models.CharField(help_text='Patient NID (National Identification Number)', max_length=20)),
                ('patient_name', models.CharField(help_text='Name of the Patient', max_length=100)),
                ('medication', models.CharField(blank=True, choices=[('paracetamol', 'Paracetamol'), ('ibuprofeno', 'Ibuprofeno'), ('amoxicilina', 'Amoxicilina'), ('azitromicina', 'Azitromicina'), ('metformina', 'Metformina'), ('losartana', 'Losartana'), ('anlodipino', 'Anlodipino'), ('atorvastatina', 'Atorvastatina'), ('salbutamol', 'Salbutamol'), ('hidroclorotiazida', 'Hidroclorotiazida'), ('enalapril', 'Enalapril'), ('omeprazol', 'Omeprazol'), ('captopril', 'Captopril'), ('clopidogrel', 'Clopidogrel'), ('ceftriaxona', 'Ceftriaxona'), ('insulina', 'Insulina'), ('ácido acetilsalicílico', 'Ácido Acetilsalicílico (AAS)'), ('diclofenaco', 'Diclofenaco'), ('gentamicina', 'Gentamicina'), ('furosemida', 'Furosemida'), ('doxiciclina', 'Doxiciclina'), ('ciprofloxacina', 'Ciprofloxacina'), ('levotiroxina', 'Levotiroxina'), ('nifedipina', 'Nifedipina'), ('prednisolona', 'Prednisolona'), ('varfarina', 'Varfarina'), ('sinvastatina', 'Sinvastatina'), ('diazepam', 'Diazepam'), ('albuterol', 'Albuterol'), ('cetoconazol', 'Cetoconazol'), ('fluconazol', 'Fluconazol'), ('amitriptilina', 'Amitriptilina'), ('fenobarbital', 'Fenobarbital'), ('quinino', 'Quinino'), ('hidroxicloroquina', 'Hidroxicloroquina'), ('cloroquina', 'Cloroquina'), ('metildopa', 'Metildopa'), ('risperidona', 'Risperidona'), ('haloperidol', 'Haloperidol'), ('cotrimoxazol', 'Cotrimoxazol'), ('nevirapina', 'Nevirapina'), ('efavirenz', 'Efavirenz'), ('zidovudina', 'Zidovudina'), ('lamivudina', 'Lamivudina'), ('ritonavir', 'Ritonavir'), ('abacavir', 'Abacavir'), ('dolutegravir', 'Dolutegravir'), ('isoniazida', 'Isoniazida'), ('etambutol', 'Etambutol'), ('rifampicina', 'Rifampicina'), ('pirazinamida', 'Pirazinamida'), ('mebendazol', 'Mebendazol'), ('albendazol', 'Albendazol'), ('praziquantel', 'Praziquantel'), ('espironolactona', 'Espironolactona'), ('glibenclamida', 'Glibenclamida'), ('arteméter', 'Arteméter'), ('lumefantrina', 'Lumefantrina'), ('pirimetamina', 'Pirimetamina'), ('sulfadoxina', 'Sulfadoxina'), ('bupivacaína', 'Bupivacaína'), ('lidocaína', 'Lidocaína'), ('morfina', 'Morfina'), ('tramadol', 'Tramadol'), ('codeína', 'Codeína'), ('fentanil', 'Fentanil'), ('midazolam', 'Midazolam'), ('ondansetrona', 'Ondansetrona'), ('metronidazol', 'Metronidazol'), ('piperacilina', 'Piperacilina'), ('tazobactam', 'Tazobactam'), ('clindamicina', 'Clindamicina'), ('vancomicina', 'Vancomicina'), ('violeta genciana', 'Violeta Genciana'), ('dexametasona', 'Dexametasona'), ('cetamina', 'Cetamina'), ('gluconato de cálcio', 'Gluconato de Cálcio'), ('sulfato de magnésio', 'Sulfato de Magnésio'), ('fexofenadina', 'Fexofenadina'), ('loratadina', 'Loratadina'), ('cetirizina', 'Cetirizina'), ('digoxina', 'Digoxina'), ('bisoprolol', 'Bisoprolol'), ('atenolol', 'Atenolol'), ('verapamil', 'Verapamil'), ('metilprednisolona', 'Metilprednisolona'), ('espiramicina', 'Espiramicina'), ('glicose', 'Glicose'), ('solução eletrolítica', 'Solução Eletrolítica'), ('albumina', 'Albumina'), ('adrenalina', 'Adrenalina'), ('noradrenalina', 'Noradrenalina'), ('dopamina', 'Dopamina'), ('teofilina', 'Teofilina'), ('ipratropio', 'Ipratrópio'), ('montelucaste', 'Montelucaste'), ('sertralina', 'Sertralina'), ('fluoxetina', 'Fluoxetina'), ('citalopram', 'Citalopram'), ('carbamazepina', 'Carbamazepina'), ('ácido valpróico', 'Ácido Valpróico'), ('levetiracetam', 'Levetiracetam'), ('bicarbonato de sódio', 'Bicarbonato de Sódio')], help_text='Select medication from MISAU official database', max_length=50)),
                ('medication_text', models.CharField(blank=True, help_text='Enter medication if not listed in MISAU database', max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Amount of medication prescribed', max_digits=5)),
                ('unit', models.CharField(choices=[('ml', 'Milliliters (ml)'), ('g', 'Grams (g)'), ('mg', 'Milligrams (mg)'), ('tablets', 'Tablets')], help_text='Unit of measurement (e.g., ml, g, mg)', max_length=20)),
                ('administration_route', models.CharField(choices=[('oral', 'Oral'), ('intravenosa', 'Intravenosa'), ('intramuscular', 'Intramuscular'), ('subcutanea', 'Subcutânea'), ('topica', 'Tópica'), ('inhalatoria', 'Inalatória'), ('sublingual', 'Sublingual'), ('retal', 'Retal'), ('transdermica', 'Transdérmica'), ('oftalmica', 'Oftálmica'), ('otica', 'Ótica'), ('nasal', 'Nasal'), ('vaginal', 'Vaginal'), ('intranasal', 'Intranasal'), ('intradermica', 'Intradérmica'), ('intra-articular', 'Intra-articular'), ('intratecal', 'Intratecal'), ('intraperitoneal', 'Intraperitoneal')], help_text='Route of administration', max_length=20)),
                ('daily_dose', models.CharField(choices=[('uma_vez', 'Uma vez ao dia'), ('duas_vezes', 'Duas vezes ao dia'), ('tres_vezes', 'Três vezes ao dia'), ('quatro_vezes', 'Quatro vezes ao dia'), ('a_cada_6_horas', 'A cada 6 horas'), ('a_cada_8_horas', 'A cada 8 horas'), ('a_cada_12_horas', 'A cada 12 horas'), ('a_cada_24_horas', 'A cada 24 horas')], help_text='How many times per day the medication should be taken', max_length=20)),
                ('number_of_days', models.PositiveIntegerField(help_text='Number of days the medication should be taken')),
                ('comment', models.TextField(blank=True, help_text='Additional instructions or comments')),
            ],
        ),
    ]
